server:
  port: 8081

spring:
  datasource:
#   url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/test"
#   username: ${MYSQL_USER:root}
#   password: ${MYSQL_PASSWORD:root}

    url: "jdbc:mysql://localhost:3306/base_spring"
    username: root
    password: 130902thuc
    jpa:
      hibernate:
      ddl-auto: none
      show-sql: true

  data:
    redis:
      host: 162.248.102.236
      port: 6379
      timeout: 12m
      jedis:
        pool:
          max-active: 1
          max-idle: 25
          max-wait: 30000ms
          min-idle: 5
      ssl:
        enabled: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

logging:
  level:
    org.springframework.cache: DEBUG

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  accessExpireTime: 3600000 # in second
  refreshExpireTime:  360000  # in seconds

checkin:
  allowed-time-ranges:
    - "09:00-11:00"
    - "19:00-21:00"
  point-awards:
    1: 1
    2: 2
    3: 3
    4: 5
    5: 8
    6: 13
    7: 21
  max-checkins-per-month: 7


